### ISSUE TITLE
how to view the keypoint matching in picture

### ISSUE THREAD

**Issue by BanaBear** [Lu-Feng/SelaVPR#3]
Thanks for sharing your work, your paper was very interesting and the results are also very impressive!
i have a question that how to view the keypoint matching in picture, the variable kps is defined but bot used, could you please tell me how to get the matching keypoints? thank you very much!

**Comment by Lu-Feng** [comment]
Thanks for your interest in our work. You can refer to the repo of Patch-NetVLAD to visualize the matching keypoints. We also plan to upload the related code in the next few days.

**Comment by jxhoh** [comment]
> 感谢您分享您的工作，您的论文非常有趣，结果也令人印象深刻！我有一个问题，如何查看图片中的关键点匹配，定义了变量KPS，但使用了机器人，您能告诉我如何获取匹配的关键点吗？谢谢！

"Have you solved this one? I've been looking at it for a while, but I couldn't quite understand it, especially when comparing it to Patch-NetVLAD. How should I write an example for this?"

**Comment by Lu-Feng** [comment]
Hi, @BanaBear @jxhoh . I have add the [visualize_pairs.py](https://github.com/Lu-Feng/SelaVPR/blob/main/visualize_pairs.py) for the visualization of matched pairs. You can use it as
```
python visualize_pairs.py --datasets_folder=./ --resume=/home/lufeng/data/VPR/SelaVPR-main/SelaVPR_msls.pth
```

**Comment by jxhoh** [comment]
> Hi, @BanaBear @jxhoh . I have add the [visualize_pairs.py](https://github.com/Lu-Feng/SelaVPR/blob/main/visualize_pairs.py) for the visualization of matched pairs. You can use it as
> 
> ```
> python visualize_pairs.py --datasets_folder=./ --resume=/home/lufeng/data/VPR/SelaVPR-main/SelaVPR_msls.pth
> ```
thank you for you help
