### ISSUE TITLE
How do I try to search with my own data, I want to take my own data set and organize it in that form

### ISSUE THREAD

**Issue by jxhoh** [Lu-Feng/SelaVPR#4]
self.database_utms = np.array([(path.split("@")[1], path.split("@")[2]) for path in self.database_paths]).astype(np.float)
        self.queries_utms  = np.array([(path.split("@")[1], path.split("@")[2]) for path in self.queries_paths]).astype(np.float)
        I don't understand these two lines of code

**Comment by Lu-Feng** [comment]
The dataset preparation follows [visual geo-localization benchmark](https://github.com/gmberton/VPR-datasets-downloader). If you want to use it on your own dataset, you'll need to rewrite the image names in this standard format:
`@ UTM_east @ UTM_north @ UTM_zone_number @ UTM_zone_letter @ latitude @ longitude @ pano_id @ tile_num @ heading @ pitch @ roll @ height @ timestamp @ note @ extension`
where the only indispensable values are UTM coordinates (UTM_east and UTM_north). The character `@` is used as the separator. So we can use `path.split("@")[1], path.split("@")[2]` to get the UTM coordinates, which are further used to calculate geographical distances.

**Comment by Lu-Feng** [comment]
If your images are labeled by latitude and longitude, you need to convert it to get UTM coordinates. If they are annotated by frame-level correspondence, you can create pseudo UTM coordinates. For example, you can rewrite the name of the i-th image in the Nordland-test dataset to `@i@0@@@@@@@@@@@@@.jpg`, and set the evaluation parameter `val_positive_dist_threshold` to 2 (i.e. the threshold is 2 frames).

**Comment by jxhoh** [comment]
假如我的数据，没有任何标识，我就是想从一大堆图片中找出 最相似的图像呢，虽然这样听起来不像地理定位，但是有时候更多的场景是盲定位吧
