### ISSUE TITLE
Nordland

### ISSUE THREAD

**Issue by LKELN** [Lu-Feng/SelaVPR#6]
By how many frames is your nordland dataset extracted? I got the results by 10 frames 87.2, 93.9, 95.6.

**Comment by Lu-Feng** [comment]
Hello, we use Nordland-test for the experiments, which contains 3450  images in database/queries. The threshold is set to ±2 frames.

**Comment by LKELN** [comment]
Can you provide the code to extract them?

**Comment by Lu-Feng** [comment]
You can download the dataset [here](https://drive.google.com/drive/folders/1idnJt7w2JFvva9IL0y390ZUkKASz-6B8) and rewrite the image name as [this](https://github.com/Lu-Feng/SelaVPR/issues/4#issuecomment-2042033249). If you need more help for this issue, you can add me on WeChat.

**Comment by LKELN** [comment]
What's your WeChat?

**Comment by Lu-Feng** [comment]
1600925872
