### ISSUE TITLE
Questions about image input size and model initialization

### ISSUE THREAD

**Issue by APPZ99** [Lu-Feng/SelaVPR#7]
Hello! Thank you for such an impressive work.
I have some questions about the model input in this work and hope to get your help.

In file `network.py`, when getting the model backbone, the input size of the image is set to 518, and the subsequent tests are all scaled to (224, 224). Can the maximum input image be (518, 518)?
```
if args.registers:
        backbone = vit_large(patch_size=14,img_size=518,init_values=1,block_chunks=0, num_register_tokens=4)
else:
        backbone = vit_large(patch_size=14,img_size=518,init_values=1,block_chunks=0)
```

For images with large length and width differences, such as (1200, 680), when they are transformed into a rectangular size of (224, 224), the information of the longer side dimension of the image will be lost. Can I scale them down proportionally and input them into the model while being divisible by patch_size? That is, convert (1200, 680) to (588, 336) (divisible by 14).

Since I have just started to learn about ViT models, many basic questions are not clear to me. I hope to get your reply. Thank you!

**Comment by Lu-Feng** [comment]
Hello, thanks for your interest in our work. The DINOv2/ViT backbone is able to receive input images of 588×336 (divisible by 14). However, this results in a change in the number of output local features. So you need to make three adjustments to the parameters in the code:
- Line 48 in parser.py: [224,224] --> [588,336]
- Line 49 in parser.py: [61,61,128] --> [165,93,128]
- Line 62 in network.py: (-1,16,16,1024) --> (-1,42,24,1024)

**Comment by APPZ99** [comment]
> Hello, thanks for your interest in our work. The DINOv2/ViT backbone is able to receive input images of 588×336 (divisible by 14). However, this results in a change in the number of output local features. So you need to make three adjustments to the parameters in the code:
> 
> * Line 48 in parser.py: [224,224] --> [588,336]
> * Line 49 in parser.py: [61,61,128] --> [165,93,128]
> * Line 62 in network.py: (-1,16,16,1024) --> (-1,42,24,1024)

Thanks for your reply!
So in theory, I only need to make sure that the image format size is divisible by patch_size, and I don't need to retrain the network?
Will this affect the output of the network?

At the same time, I would like to ask if you can provide a method to obtain the heat map so that I can verify the output effect myself. Thank you very much!

**Comment by Lu-Feng** [comment]
Yes. The image resolution need to be divisible by patch_size. You don't need to retrain the model, but retraining may achieve better results. The code for heat map visualization has not yet been collated. You can implement it according to the paper description.

**Comment by APPZ99** [comment]
Thanks again for your help!
